### ISSUE TITLE
1.20.1 please

### ISSUE THREAD

**Issue by IZeeXeS** [emilyy-dev/wets#3]

**Comment by emilyy-dev** [comment]
c4eb1b5eac7a2e026234b698012c0ce48b19ba84, update published on modrinth

**Comment by LokeYourC3PH** [comment]
Thanks so much, there wasn't really an alternative to FAWS (Fast Async WorldEdit) for Fabric, glad that someone made a simple equivalent that'll prevent lag. Any recommended values @emilyy-dev ?
